# Generated by Django 5.0.1 on 2024-02-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('items', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
